#!/bin/sh

set -e

case "$1" in
  purge)
	if [ -d /var/lib/shadowtun ]; then
	  rm -rf /var/lib/shadowtun
	fi
	if [ -d /var/run/shadowtun ]; then
	  rm -rf /var/run/shadowtun
	fi
  ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d shadowtun remove >/dev/null
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask shadowtun.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge shadowtun.service >/dev/null
		deb-systemd-helper unmask shadowtun.service >/dev/null
	fi
fi
# End automatically added section

